context:
  version: "0.5.0"

package:
  name: bibtex-updater
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/b/bibtex_updater/bibtex_updater-${{ version }}.tar.gz
  sha256: 1a10dce52fe0a8cda0c602914ae8415b8e1be5b4a4182d85394a233936b03833

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0
  python:
    entry_points:
      - bibtex-update = bibtex_updater.cli.updater_cli:main
      - bibtex-check = bibtex_updater.cli.fact_checker_cli:main
      - bibtex-filter = bibtex_updater.cli.filter_cli:main
      - bibtex-zotero = bibtex_updater.cli.zotero_cli:main
      - bibtex-zotero-organize = bibtex_updater.cli.zotero_organizer_cli:main
      - bibtex-obsidian-keywords = bibtex_updater.cli.obsidian_keywords_cli:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >=${{ python_min }}
    - bibtexparser >=1.4.0
    - requests >=2.28.0
    - crossref_commons_py >=0.0.7
    - httpx >=0.24.0
    - rapidfuzz >=3.0.0
    - scholarly >=1.7.0
    - pyzotero >=1.5.0
    - pyyaml >=6.0
    - sentence-transformers >=2.2.0

tests:
  - python:
      imports:
        - bibtex_updater
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/rpatrik96/bibtexupdater
  summary: Replace preprint BibTeX entries with published versions and validate bibliography references.
  description: |
    Tools for managing BibTeX bibliographies: automatically update preprints to published versions, validate references against external databases, and filter to only cited references.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - claudiushaag
